Feature ending to game
s-hayashi1104/tpa-03-typing-tutor pull request #1
Opened 2018-09-29 15:39 UTC by s-hayashi1104

入力した値の正誤を保持するプロパティの追加
ゲームを終了する用に改修
ゲーム終了時に結果を表示する用に改修

2018-10-01 15:37 UTC, clonable-eden commented
@s-hayashi1104 確認しました。
TypingTutorViewクラスに`announceResults`を追加したのは非常にgoodです！
以下確認してほしいことを列挙しました。

1. タイピングを終了しても文字を打ち続けることができてしまいます（一度ご自身で確認してみてください）。TypingTutorGameクラス側で終了したら処理しないような制御をしなければなりません。
2. View側に制御のロジックを入れるのはちょっといただけないかもしれません。ゲームを司る（=>正解/不正解のカウントアップや、終了判定を行う）のはGameクラス側の方が良い気がしませんか？Viewはあくまでも描画をする関数だけを持った方がよく、「何を表示するか」についてはGame側から与えてあげるとよい機能分割になるのではないでしょうか。

2018-10-01 17:37 UTC, clonable-eden requested changes
@s-hayashi1104 コメントしましたmm

2018-10-01 17:37 UTC, clonable-eden commented on public/js/components/TypingTutorView.js
> +  announceResults(keyCorrect, totalLength) {
ユーザが入力した内容は、結果として見せておいた方がよいかな。そのうえで「N%の正解率でしたよ」の方がゲームとしてユーザフレンドリーな気がします。

2018-10-01 17:37 UTC, clonable-eden commented on public/js/components/TypingTutorGame.js
> +    if (this.targetText.length - 1 === this.keyCorrect + this.keyInCorrect) {
`if (!this.isRoundInProgress) return;` この制御文よりも前に書くと、ゲーム終了後にhandleKeyStrokeに入ってきたとき、常にif文の中が実行されてしまいます。見た目的に問題はありませんが、returnする条件判定は最初に行うべきだと思います。

2018-10-01 17:37 UTC, clonable-eden commented on public/js/components/TypingTutorGame.js
> +    if (this.targetText.length - 1 === this.keyCorrect + this.keyInCorrect) {
その前提に立つと、そもそもisRoundInProgressのフラグを下げ、announceResultsを呼び出す位置はここでよいのでしょうか？

そもそもrenderKeystrokeの後にしなかった理由はなんでしょうか？

2018-10-03 05:35 UTC, clonable-eden reviewed
@s-hayashi1104 機能的にはLGTMですが2つコメントしました。確認お願いしますmm

2018-10-03 05:35 UTC, clonable-eden commented on public/js/components/TypingTutorView.js
> +    const contaier = document.querySelector('.learner-keystrokes');
typoかな container

2018-10-03 05:35 UTC, clonable-eden commented on public/js/components/TypingTutorView.js
> +    this.clearKeystrokes();
これ呼ぶと結果がクリアされちゃいませんか？
結果を残した上で、スコアを表示してあげるのが親切かな、というのを前回指摘した記憶があります。

2018-10-04 00:55 UTC, clonable-eden commented
@s-hayashi1104 よさそうです！1つ気づいてしまったのですが、2回連続でゲームをするとどうなりますかね？（パッとコードを見た感じだとDOM的に前回の結果=announceResultの内容がクリアされないように見えます）

2018-10-04 04:48 UTC, s-hayashi1104 commented
@clonable-eden
実際に動かして検証しましたが、問題はありませんでした！
handleStartRound() の中でthis.clearKeystrokes()を呼んでいるからだと思います！

2018-10-04 04:53 UTC, clonable-eden commented
@s-hayashi1104 おｋです！（指摘ミスってすいません）
マージしましょう！

2018-10-04 05:16 UTC, merged